kind: Deployment
apiVersion: apps/v1
metadata:
  name: xmen-meli-web
  labels:
    app: xmen-meli-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xmen-meli-web
  template:
    metadata:
      labels:
        app: xmen-meli-web
    spec:
      containers:
        - name: xmen-meli-web
          image: matiasresca/xmen-meli-web:latest
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xmen-meli-web
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 80
  selector:
    app: xmen-meli-web